@LightsControllerAPI_HostAddress = https://localhost:5042
#@LightsAPIHost = https://localhost:5042
@LightsAPIHost = https://localhost:5042

# OpenAPI Description
GET {{LightsAPIHost}}/openapi/v1/openapi.json
###
# Get All the lights
GET {{LightsAPIHost}}/lights
###
# Get All the rooms
GET {{LightsAPIHost}}/rooms
###

# Living Room Lights ------------------------------------------------
# Switch on the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
[{
  "LightId": 0,
  "State": "On"
},
{
  "LightId": 1,
  "State": "On"
},
{
  "LightId": 2,
  "State": "On"
}]
###

# Adjust the color of the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
[{
  "LightId": 0,
  "Color": "FF0000"
},
{
  "LightId": 1,
  "Color": "FF0000"
}]
###

# reset the color of the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
[{
  "LightId": 0,
  "Color": "ffffff"
},
{
  "LightId": 1,
  "Color": "ffffff"
}]
###
# Adjust the brightness of the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [0, 1, 2],
  "Brightness": 50
}
###
# Adjust back the brightness of the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [0, 1, 2],
  "Brightness": 100
}
###

# Switch off the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [0, 1, 2],
  "State": "Off"
}
###

# Office Lights -----------------------------------------------------
# Switch on the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [8, 9],
  "State": "On"
}
###
#Dim the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [8, 9],
  "Brightness": 5
}
###

###
# Switch off the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [8, 9],
  "State": "Off"
}
###
# Kitchen Lights -----------------------------------------------------
# Switch on the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [3, 4, 5],
  "State": "On"
}
###
# Switch off the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [3, 4, 5],
  "State": "Off"
}
###
# Downstairs Bathroom -----------------------------------------------------
# Switch on the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [6],
  "State": "On"
}
###
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [6],
  "State": "Off"
}
###
# Laundry room -----------------------------------------------------
# Switch on the lights
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [7],
  "State": "On"
}
###
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [7],
  "State": "Off"
}
###
# Stairs -----------------------------------------------------
# Switch on the light
PATCH {{LightsControllerAPI_HostAddress}}/lights
Content-Type: application/json
{
  "LightIds": [10],
  "State": "On"
}
###
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [10],
  "State": "Off"
}
###
# Master Bedroom -----------------------------------------------------
# Switch on the light
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [11,12,13],
  "State": "On",
  "Color": "FF0000"
}
###

PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [11,12,13],
  "State": "Off"
}
###

# Turns living room ON, then half Brightness, then Blue
PATCH {{LightsAPIHost}}/lights
Content-Type: application/json
{
  "LightIds": [0, 1, 2],
  "State": "On",
  "Color": "0000FF",
  "Brightness": 50
}
###

GET {{LightsControllerAPI_HostAddress}}/house

###
